apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-pod
  name: my-pod
spec:
  containers:
  - image: alpine
    name: my-pod
    ports:
    - containerPort: 80
    resources: {}
  serviceAccountName: ckauser1-bot    
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
